### ISSUE TITLE
Threading causes error on old python versions

### ISSUE THREAD

**Issue by ajbozarth** [IBM/MAX-Image-Caption-Generator-Web-App#10]
Rich found the following error running the latest master:

```
INFO: Connecting to ML endpoint at http://localhost:5000/model/predict
INFO: Starting web server
INFO: Preparing ML metadata
Traceback (most recent call last):
  File "app.py", line 190, in <module>
    main()
  File "app.py", line 181, in main
    prepare_metadata()
  File "app.py", line 115, in prepare_metadata
    threads.clear()
AttributeError: 'list' object has no attribute 'clear'
```

This is caused since `list.clear()` is a python 3 function. We should either change this line for version compatibility or add a python 3 requirement to the project.

**Comment by stevemart** [comment]
+1, a reason for a linter that tests for py27 and py36 :)
